export enum ErrorCode {
  ACTION_NOT_ALLOWED = "action_not_allowed",
  BAD_ENV = "bad_env",
  BAD_JSON = "bad_json",
  BAD_REQUEST = "bad_request",
  DECISION_NOT_FOUND = "decision_not_found",
  FUNCTION_NOT_ALLOWED = "function_not_allowed",
  HANDLER_FAILED = "handler_failed",
  INTERNAL_ERROR = "internal_error",
  INVALID_DECISION_INPUT = "INVALID_DECISION_INPUT",
  INVALID_JSON = "invalid_json",
  INVALID_SERVICE_ROLE_KEY = "invalid_service_role_key",
  MANDATE_INVALID = "mandate_invalid",
  METHOD_NOT_ALLOWED = "method_not_allowed",
  MISSING_CLAIM = "MISSING_CLAIM",
  MISSING_DECISION_REF = "MISSING_DECISION_REF",
  MISSING_ENV = "missing_env",
  MISSING_GOAL = "MISSING_GOAL",
  MISSING_HANDLE = "MISSING_HANDLE",
  MISSING_MESSAGE = "missing_message",
  NOT_FOUND = "not_found",
  NO_SCHEMA = "no_schema",
  ROUTER_FAILED = "router_failed",
  SERVER_ENV_INVALID = "server_env_invalid",
  SERVER_ENV_MISSING = "server_env_missing",
  SUPABASE_ERROR = "supabase_error",
  UNAUTHORIZED = "unauthorized",
  FORBIDDEN = "forbidden",
  UPSTREAM_ERROR = "upstream_error",
  UPSTREAM_EXCEPTION = "upstream_exception",
}

export const ERROR_CODE_VALUES = Object.values(ErrorCode);
