import { useState } from "react";
import AdminLayout from "@/components/AdminLayout";
import AgentWorkItem, { WorkItem } from "@/components/AgentWorkItem";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import {
  GitBranch,
  TrendingUp,
  Target,
  Zap,
  CheckCircle,
  RefreshCw,
  Brain,
  Loader2,
  ArrowRight,
  Users,
  MousePointerClick,
  ShoppingCart,
  Sparkles,
} from "lucide-react";

interface FunnelStage {
  name: string;
  visitors: number;
  conversions: number;
  dropOff: number;
}

const mockFunnelStages: FunnelStage[] = [
  { name: "Landing Page", visitors: 1000, conversions: 650, dropOff: 35 },
  { name: "Calculator", visitors: 650, conversions: 320, dropOff: 51 },
  { name: "Demo Request", visitors: 320, conversions: 145, dropOff: 55 },
  { name: "Contact Form", visitors: 145, conversions: 52, dropOff: 64 },
  { name: "Booked Call", visitors: 52, conversions: 38, dropOff: 27 },
];

const mockWorkItems: WorkItem[] = [
  {
    id: "1",
    title: "AI: High Drop-off Detected at Calculator Stage",
    description: "51% drop-off at calculator stage. AI recommends simplifying inputs and adding progress indicator.",
    type: "approval",
    status: "pending",
    priority: "urgent",
    createdAt: new Date().toISOString(),
    details: "Analysis:\n- Users spending avg 45s before abandoning\n- Mobile users 2x more likely to drop\n- Recommendation: Add 'quick estimate' option that requires only 2 fields",
  },
  {
    id: "2",
    title: "A/B Test Ready: CTA Button Variants",
    description: "3 CTA variants generated by AI ready for testing on hero section.",
    type: "approval",
    status: "pending",
    priority: "high",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    details: "Variant A: 'Get Your Free Quote Now' (Current)\nVariant B: 'See How Much You're Losing →' (Curiosity)\nVariant C: 'Start Capturing Missed Calls' (Action)",
  },
  {
    id: "3",
    title: "New Retargeting Flow Proposed",
    description: "AI designed 5-step retargeting sequence for calculator abandoners.",
    type: "review",
    status: "pending",
    priority: "medium",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    details: "Day 1: Email with personalized calculation\nDay 3: Case study email\nDay 5: Limited time offer\nDay 7: Final reminder\nDay 14: Re-engagement with new value prop",
  },
  {
    id: "4",
    title: "Mobile Funnel Optimization",
    description: "AI detected mobile conversion rate 40% lower than desktop. Recommending changes.",
    type: "approval",
    status: "pending",
    priority: "high",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
];

const AdminAgentFunnels = () => {
  const [workItems, setWorkItems] = useState<WorkItem[]>(mockWorkItems);
  const [loading, setLoading] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiResult, setAiResult] = useState<string>("");
  const [customPrompt, setCustomPrompt] = useState("");
  const { toast } = useToast();

  const pendingCount = workItems.filter(w => w.status === "pending").length;
  const overallConversion = ((mockFunnelStages[mockFunnelStages.length - 1].conversions / mockFunnelStages[0].visitors) * 100).toFixed(1);

  const handleApprove = (id: string) => {
    setWorkItems(prev => 
      prev.map(item => 
        item.id === id ? { ...item, status: "approved" as const } : item
      )
    );
    toast({
      title: "Optimization Approved",
      description: "Changes will be implemented.",
    });
  };

  const handleDeny = (id: string, reason: string) => {
    setWorkItems(prev => 
      prev.map(item => 
        item.id === id ? { ...item, status: "denied" as const } : item
      )
    );
    toast({
      title: "Optimization Rejected",
      description: `Reason: ${reason}`,
      variant: "destructive",
    });
  };

  const handleDiscuss = (id: string) => {
    toast({
      title: "Opening CEO Discussion",
      description: "Redirecting to CEO Agent chat...",
    });
  };

  const handleRefresh = async () => {
    setLoading(true);
    await new Promise(resolve => setTimeout(resolve, 1000));
    setLoading(false);
    toast({ title: "Refreshed", description: "Funnel data updated." });
  };

  const runAIAnalysis = async (type: string) => {
    setAiLoading(true);
    setAiResult("");
    
    try {
      const { data, error } = await supabase.functions.invoke('funnel-ai', {
        body: {
          type,
          funnelData: {
            name: "Main Sales Funnel",
            stages: mockFunnelStages,
          },
          metrics: {
            visitors: mockFunnelStages[0].visitors,
            leads: mockFunnelStages[3].conversions,
            conversions: mockFunnelStages[4].conversions,
            conversionRate: overallConversion,
            bounceRate: 35,
            avgTimeOnPage: "2:34",
          },
        },
      });

      if (error) throw error;
      
      setAiResult(data.result);
      toast({
        title: "AI Analysis Complete",
        description: "Review the recommendations below.",
      });
    } catch (error: any) {
      console.error("AI analysis error:", error);
      toast({
        title: "Analysis Failed",
        description: error.message || "Failed to run AI analysis",
        variant: "destructive",
      });
    } finally {
      setAiLoading(false);
    }
  };

  const runCustomAnalysis = async () => {
    if (!customPrompt.trim()) return;
    
    setAiLoading(true);
    setAiResult("");
    
    try {
      const { data, error } = await supabase.functions.invoke('funnel-ai', {
        body: {
          type: "analyze",
          funnelData: {
            name: "Custom Analysis",
            context: customPrompt,
          },
          metrics: {
            visitors: mockFunnelStages[0].visitors,
            conversions: mockFunnelStages[4].conversions,
            conversionRate: overallConversion,
          },
        },
      });

      if (error) throw error;
      
      setAiResult(data.result);
    } catch (error: any) {
      toast({
        title: "Analysis Failed",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setAiLoading(false);
    }
  };

  return (
    <AdminLayout 
      title="Funnels Agent" 
      subtitle="AI-powered conversion optimization and flow management"
    >
      {/* Funnel Visualization */}
      <Card className="mb-8 overflow-hidden">
        <CardHeader className="border-b bg-gradient-to-r from-accent/10 to-primary/10">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-accent/20">
                <GitBranch className="h-5 w-5 text-accent" />
              </div>
              <div>
                <CardTitle>Main Sales Funnel</CardTitle>
                <p className="text-sm text-muted-foreground">Live conversion tracking</p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-3xl font-bold text-accent">{overallConversion}%</p>
              <p className="text-sm text-muted-foreground">Overall Conversion</p>
            </div>
          </div>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="flex items-center justify-between overflow-x-auto pb-4">
            {mockFunnelStages.map((stage, index) => (
              <div key={stage.name} className="flex items-center">
                <div className="flex flex-col items-center min-w-[120px]">
                  <div className={`w-16 h-16 rounded-full flex items-center justify-center text-lg font-bold ${
                    stage.dropOff > 50 ? 'bg-destructive/20 text-destructive' : 
                    stage.dropOff > 30 ? 'bg-yellow-500/20 text-yellow-600' : 
                    'bg-green-500/20 text-green-600'
                  }`}>
                    {stage.conversions}
                  </div>
                  <p className="text-sm font-medium mt-2 text-center">{stage.name}</p>
                  <p className="text-xs text-muted-foreground">
                    {stage.dropOff}% drop-off
                  </p>
                </div>
                {index < mockFunnelStages.length - 1 && (
                  <ArrowRight className="h-6 w-6 text-muted-foreground mx-2 flex-shrink-0" />
                )}
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-lg bg-accent/20">
                <Users className="h-6 w-6 text-accent" />
              </div>
              <div>
                <p className="text-2xl font-bold">{mockFunnelStages[0].visitors}</p>
                <p className="text-sm text-muted-foreground">Visitors</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-lg bg-primary/20">
                <MousePointerClick className="h-6 w-6 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold">{mockFunnelStages[3].conversions}</p>
                <p className="text-sm text-muted-foreground">Leads</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-lg bg-green-500/20">
                <ShoppingCart className="h-6 w-6 text-green-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{mockFunnelStages[4].conversions}</p>
                <p className="text-sm text-muted-foreground">Conversions</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-lg bg-yellow-500/20">
                <Target className="h-6 w-6 text-yellow-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{pendingCount}</p>
                <p className="text-sm text-muted-foreground">Pending Actions</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* AI Analysis Section */}
      <Card className="mb-8 border-accent/30">
        <CardHeader className="bg-gradient-to-r from-accent/5 to-transparent">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-accent/20">
              <Brain className="h-5 w-5 text-accent" />
            </div>
            <div>
              <CardTitle className="flex items-center gap-2">
                AI Conversion Optimizer
                <Sparkles className="h-4 w-4 text-accent" />
              </CardTitle>
              <p className="text-sm text-muted-foreground">Real-time analysis and recommendations</p>
            </div>
          </div>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
            <Button
              variant="outline"
              className="h-auto py-3 flex flex-col gap-1"
              onClick={() => runAIAnalysis("analyze")}
              disabled={aiLoading}
            >
              <TrendingUp className="h-5 w-5" />
              <span className="text-xs">Analyze Funnel</span>
            </Button>
            <Button
              variant="outline"
              className="h-auto py-3 flex flex-col gap-1"
              onClick={() => runAIAnalysis("generate_ab_test")}
              disabled={aiLoading}
            >
              <Zap className="h-5 w-5" />
              <span className="text-xs">Generate A/B Tests</span>
            </Button>
            <Button
              variant="outline"
              className="h-auto py-3 flex flex-col gap-1"
              onClick={() => runAIAnalysis("optimize_copy")}
              disabled={aiLoading}
            >
              <Target className="h-5 w-5" />
              <span className="text-xs">Optimize Copy</span>
            </Button>
            <Button
              variant="outline"
              className="h-auto py-3 flex flex-col gap-1"
              onClick={() => runAIAnalysis("suggest_flow")}
              disabled={aiLoading}
            >
              <GitBranch className="h-5 w-5" />
              <span className="text-xs">Suggest Flow</span>
            </Button>
          </div>

          <div className="space-y-3">
            <Textarea
              placeholder="Ask AI anything about your funnel... e.g., 'How can I reduce drop-off at the calculator stage?'"
              value={customPrompt}
              onChange={(e) => setCustomPrompt(e.target.value)}
              className="min-h-[80px]"
            />
            <Button 
              onClick={runCustomAnalysis} 
              disabled={aiLoading || !customPrompt.trim()}
              className="w-full"
            >
              {aiLoading ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Analyzing...
                </>
              ) : (
                <>
                  <Brain className="h-4 w-4 mr-2" />
                  Ask AI
                </>
              )}
            </Button>
          </div>

          {aiResult && (
            <div className="mt-6 p-4 bg-muted rounded-lg">
              <h4 className="font-semibold mb-3 flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-accent" />
                AI Recommendations
              </h4>
              <div className="prose prose-sm max-w-none text-foreground">
                <pre className="whitespace-pre-wrap text-sm font-sans">{aiResult}</pre>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Work Items */}
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-xl font-semibold">Optimization Queue</h2>
        <Button variant="outline" size="sm" onClick={handleRefresh} disabled={loading}>
          <RefreshCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      <Tabs defaultValue="pending" className="space-y-4">
        <TabsList>
          <TabsTrigger value="pending">
            Pending
            {pendingCount > 0 && <Badge variant="secondary" className="ml-2">{pendingCount}</Badge>}
          </TabsTrigger>
          <TabsTrigger value="completed">Completed</TabsTrigger>
          <TabsTrigger value="all">All</TabsTrigger>
        </TabsList>

        <TabsContent value="pending" className="space-y-4">
          {workItems.filter(w => w.status === "pending").length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <CheckCircle className="h-12 w-12 text-green-500 mx-auto mb-4" />
                <p className="text-lg font-medium">Funnel optimized!</p>
                <p className="text-muted-foreground">No pending optimizations.</p>
              </CardContent>
            </Card>
          ) : (
            workItems.filter(w => w.status === "pending").map(item => (
              <AgentWorkItem
                key={item.id}
                item={item}
                onApprove={handleApprove}
                onDeny={handleDeny}
                onDiscuss={handleDiscuss}
              />
            ))
          )}
        </TabsContent>

        <TabsContent value="completed" className="space-y-4">
          {workItems.filter(w => w.status !== "pending").map(item => (
            <AgentWorkItem key={item.id} item={item} />
          ))}
        </TabsContent>

        <TabsContent value="all" className="space-y-4">
          {workItems.map(item => (
            <AgentWorkItem
              key={item.id}
              item={item}
              onApprove={handleApprove}
              onDeny={handleDeny}
              onDiscuss={handleDiscuss}
            />
          ))}
        </TabsContent>
      </Tabs>
    </AdminLayout>
  );
};

export default AdminAgentFunnels;
